apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: ghcr.io/alexjose/lara-k8s:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: github-container-registry