name: Build PHP FPM Image

on:
  push:
    paths:
        - '.docker/php-cli/Dockerfile'
jobs:
 
  build:
    name: Build
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:.docker/php-cli"
          push: true
          tags: |
            ghcr.io/alexjose/lara-k8s-php-fpm:latest
            ghcr.io/alexjose/lara-k8s-php-fpm:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max